### ISSUE TITLE
TYPO3 v12 compatibility

### ISSUE THREAD

**Issue by jimping** [FriendsOfTYPO3Headless/headless_bootstrap_package#54]
Hey there,

will this package offer support for TYPO3 Version 12? I am using it in some projects with TYPO3 Version 11. 

Thank you :)

**Comment by svenpet90** [comment]
@jimping Thanks for your question! and apologies for not answering it any earlier!

I just moved houses and the end of last year.. so quite a lot to do.. 

Ill have a look at making this v12 compatilbe! Shouldn't be that hard :) #famousLastWords

**Comment by svenpet90** [comment]
I just released [v3](https://github.com/FriendsOfTYPO3Headless/headless_bootstrap_package/releases/tag/v3.0.0) of this extension.

Except for minor tweaks in the Unitstests there was not much else to do to make this work.
Please feel free to give it a try and report any bugs you might encounter :-)

Have a good one!
